### ISSUE TITLE
Teraranger One to I2c of pixfalcon

### ISSUE THREAD

**Issue by ChunJyeBehBeh** [Terabee/teraranger_array#44]
I have connect my teraranger one to i2c pixfalcon. Anything that I need to change inside the code? from /dev/ttyUSB0 to ?

After I run "rosrun teraranger one "(why not "rosrun teraranger teraranger_one"), 

terminate called after throwing an instance of 'serial::IOException'
  what():  IO Exception (2): No such file or directory, file /tmp/binarydeb/ros-kinetic-serial-1.2.1/src/impl/unix.cc, line 151.
Aborted (core dumped)

it show this error. How to solve it? I would like to let the terarange one publish data to mavros .

**Comment by msadowski** [comment]
If you connect the TeraRanger to pixfalcon then the only thing you need to set on Pixhawk side are the the Rangefinder type in case of Px4. For more information you can refer to [our docs](https://www.terabee.com/connection-to-pixhawk-autopilots-teraranger-one/). You will just need to make sure to properly wire the connector.

If you are able to successfully observe the rangefinder distance as per the description in the documentation I mentioned above you can attempt to interface your board with ROS. I would suggest connecting your ROS enabled computer to a serial port on Pixhawk and launch mavros. Once you have mavros running you should be able to view the distance messages from the sensors in mavros messages. In this setup you don't need to use our ROS drivers at all. [Here](https://pixhawk.org/dev/ros/getting_started_tutorial) is some information from the PX4 project about ROS setup: 

However if you want to use those drivers then use the [TeraRanger package](https://github.com/Terabee/teraranger) that is meant for single sensors and plug the sensor in through the USB port to your computer. Once you correctly specify the port name the node should work.

I'll close this issue for now. If you need support with our ROS driver for a single point sensor (TeraRanger One) then please open a new issue in the TeraRanger repository.
