### ISSUE TITLE
Timeout error after Long run for TeraRanger Multiflex

### ISSUE THREAD

**Issue by David9696** [Terabee/teraranger_array#45]
Hi,

I have been using TeraRanger Multiflex for my project. I realized that after the sensor is up for long time I would get the following error:

[ERROR] [1522316203.492028494]: Timeout or error while reading serial
[ERROR] [1522316205.491701621]: Timeout or error while reading serial
[ERROR] [1522316207.491601906]: Timeout or error while reading serial
[ERROR] [1522316209.491506648]: Timeout or error while reading serial
[ERROR] [1522316211.492185395]: Timeout or error while reading serial
[ERROR] [1522316213.491492225]: Timeout or error while reading serial

The only way to solve is unplug the sensor and plug in again. May I know why? How to solve this?

Thanks.

David

**Comment by pl-kabaradjian** [comment]
UPDATE:

Hello David,

We are actively looking into your issue. In the mean time, I will lock this issue as this is already being taken care of on Terabee's support.

Best regards,

**Comment by Alex-Beh** [comment]
@pl-kabaradjian @David9696 I encountered this problem also. May I know the solution/fix for this issue?

**Comment by pl-kabaradjian** [comment]
Hello @Alex-Beh , it was quite a while ago but if I remember well we were not able to reproduce the issue in-house, despite running a multiflex for 24 hours straight. Our main hypothesis was the connection between sensor modules being interrupted by vibrations or shocks but we could never validate it.

Could you tell us a bit more about your setup using our support form ([here](https://www.terabee.com/contact/))? It will be easier for our support team to track your issue.
