### ISSUE TITLE
Display of RangeArray in Rviz

### ISSUE THREAD

**Issue by TheRobotStudio** [Terabee/teraranger_array#49]
After the transition from the old teraranger_hub_multiflex package to this new one, the message has changed from sensor_msgs/Range to the custom message RangeArray.

Do you provide a way to display that in Rviz ?

**Comment by msadowski** [comment]
We created the [teraranger_array_converter](https://github.com/Terabee/teraranger_array_converter) package that should enable you to change RangeArray into any format you want to display (point cloud, laser scan, single distances for each sensor). Once you convert RangeArray to any of those formats you should be able to display them in Rviz.

Please let me know if it worked for you and I'll close this issue.

**Comment by TheRobotStudio** [comment]
Thanks, it works for me with the individual_ranges. I'd like to use the sequential_ranges but it just display the range on the last one (range_7) of the multiflex even if I defined all of them in my URDF. However it's not related to this package so I'll open an issue in the teraranger_array_converter repo.

**Comment by msadowski** [comment]
Thanks for the update. If you keep having issues with the converter please raise an issue in the converter repository.
