### ISSUE TITLE
multiflex in ros 

### ISSUE THREAD

**Issue by ytgcljj** [Terabee/teraranger_array#52]
I bought multiflex, I want to display in ROS RVIZ, how to operate.

**Comment by pl-kabaradjian** [comment]
Hello @ytgcljj ,

By default the node "teraranger_multiflex" in package "teraranger_array" will output all the ranges in a custom RangeArray message. To be able to display those ranges in RVIZ you need to convert this message into more standards Range messages. We provide this conversion capability with the package "teraranger_array_converter". You can find examples of how to use it in both README and launch files of teraranger_array_converter.
However if you want to be able to specify your custom sensor location (to display them properly in 3D), you need to setup correctly the tf-tree. We don't provide support for this as it is setup dependent, however you can take a look at our "teraranger_description" package where there is an example of tf-tree setup for TeraRanger Tower.

Have a nice day,

Regards
Pierre-Louis Kabaradjian

**Comment by pl-kabaradjian** [comment]
Hello @ytgcljj I will close this issue if you don't see any inconvenience.
