### ISSUE TITLE
Generated RangeArray.h has hasHeader set to false

### ISSUE THREAD

**Issue by kjaget** [Terabee/teraranger_array#58]
I'm running into this in ROS Kinetic, on x64 Linux.

Even though the RangeArray .msg file defines `Header header`, it looks like the generated .h file internally doesn't recognize that the message has a header defined. Specifically, both versions of HasHeader are set to FalseType. 

This prevents it from being used in code which attempts to access that header via ros::message_traits.  In my case, I'm trying to use it with message_filter:Synchonizer

I think the issue that the header field is not the first entry in the .msg file.

**Comment by pl-kabaradjian** [comment]
Hi Kevin,
Thank you for raising this issue.

Indeed, it seems that the message generation is behaving differently when the header is the first field. It is mentioned briefly [here](http://wiki.ros.org/msg#headerSect).

We already used the synchronizer in python without issues, it was the reason why we added a header in the first place. But I guess python doesn't check for the has_header attribute.

Did you try to move the header definition at the top and see if it works?

In the case you manage to fix it, I invite you to create a pull request with your changes. We will be more than happy to review it and merge it to master.

**Comment by kjaget** [comment]
Hi, thanks for the feedback.

Yes, it looks like the problem is embedded deep in the generated c++ headers, so it is not surprising that Python behaves differently.  

I can try the experiment you suggest and will let you know the results.

**Comment by kjaget** [comment]
PR added : https://github.com/Terabee/teraranger_array/pull/59

**Comment by pl-kabaradjian** [comment]
Hi Kevin,
Just merged both PR so i'll close this issue.
Thank again you for your contributions, it is much appreciated.
Cheers!
