### ISSUE TITLE
Noise From Teraranger Multiflex

### ISSUE THREAD

**Issue by David9696** [Terabee/teraranger_array#63]
Hi,

We have been using teraranger multiflex for my project.

We realized that, sometime the output of the sensors are not very accurate and subjected to noise.

Is it possible to add in some filter function to the sensor output?

If yes, could you guide us how to do it? Thanks.

David

**Comment by pl-kabaradjian** [comment]
Hi @David9696 ,
If the output is too noisy, one classic thing to do, and fairly simple as well, is to average the last n values. The more previous values are averaged, the more stable is the output but the less reactive it is (roughly similar to a lowpass filter).
However, it is important to take only valid measurements into account, thus excluding values such as 0 or -1.

If you have more specific questions about your application, I invite you to contact our support [here](https://www.terabee.com/contact/).

Cheers,

**Comment by David9696** [comment]
Hi,

Thanks for your reply. I am not very good in CPP programming. Would you update the package with the mentioned filter? I am more than happy to help you test.

Once there is a filter in place, I think the application of this sensor would be enlarged especially in robotics domain.

**Comment by pl-kabaradjian** [comment]
Hi @David9696 ,

Adding such a filter directly in the driver is not planned yet, as this package is only aimed at outputting raw ranges from the sensor.
However, as this is a ROS package, one way to easily do this would be to create a simple python node that takes raw ranges as input and output filtered ranges.

Cheers,
