### ISSUE TITLE
Support for TeraRanger Evo Mini Array Kits

### ISSUE THREAD

**Issue by David9696** [Terabee/teraranger_array#67]
Hi, 

Is this package support TeraRanger Evo Mini Array Kits? If yes, how do configure pixel_mode and range_mode?

Thanks.

David

**Comment by Babtou67** [comment]
Hi @David9696,

Yes this package support TeraRanger Mini Array. 
Did you manage to solve your issue? 
If yes, please aware us and i will close the issue, otherwise could you contact support@terabee.com. 

Thanks,
Baptiste
